<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;NET8.0;NET10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <IncludeSymbols>False</IncludeSymbols>

    <Title>N2 Core</Title>
    <Company>Kaalenco</Company>
    <Copyright>(c) 2025 - rights reserved</Copyright>
    <Authors>gjkaal</Authors>
    <Description>Core functionality for any application</Description>

    <Product>N2.Core</Product>
    <RootNamespace>N2.Core</RootNamespace>
    <ProductName>N2 Core libraries</ProductName>

    <Version>1.6.0</Version>
    <ProductVersion>1.6.0</ProductVersion>
    <PackageVersion>1.6.0</PackageVersion>

    <PackageId>N2.Core</PackageId>
    <PackageType>Dependency</PackageType>
    <PackageLicenseExpression>AFL-3.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kaalenco/n2-core</PackageProjectUrl>

    <UserSecretsId>N2-Core-0c368d89-5cb3-4451-9c68-b79e69920a09</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <NuGetAudit>True</NuGetAudit>
    <NuGetAuditMode>All</NuGetAuditMode>
    <NuGetAuditLevel>Low</NuGetAuditLevel>
  </PropertyGroup>
  
  <PropertyGroup>
    <WarningLevel>6</WarningLevel>
    <WarningsAsErrors></WarningsAsErrors>
    <NoWarn>S1135;RCS1021;CA1040;CA1055;CA1308;CS1591;CA1002;CA1819;CA2007;CA1859;CA1812;S2094;CA1707;IDE0290;S125;RMG020;IDE0060;CA1510</NoWarn>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
  </PropertyGroup>  
  
  <PropertyGroup>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.5" />
    <PackageReference Include="System.Identitymodel.Tokens.Jwt" Version="8.17.0" />
    <PackageReference Include="System.IO.Abstractions" Version="22.1.0" />
    <PackageReference Include="N2.Core.Abstractions" Version="1.6.1" />
  </ItemGroup>

  <ItemGroup Condition="(('$(TargetFramework)'=='netstandard2.0') Or ('$(TargetFramework)'=='netstandard2.1'))">
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PubSub\" />
  </ItemGroup>

</Project>

